# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material3d',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='printing.Material')),
            ],
            bases=('printing.material',),
        ),
        migrations.CreateModel(
            name='Order3d',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='printing.Order')),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('depth', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printing_3d.Material3d')),
            ],
            bases=('printing.order',),
        ),
    ]
