# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing_3d', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order3d',
            name='depth',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order3d',
            name='height',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order3d',
            name='width',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
