# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printing_3d', '0002_auto_20170901_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order3d',
            options={'permissions': (('can_view', 'Can view'),)},
        ),
    ]
