# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing_3d', '0004_auto_20170902_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='order3d',
            name='chargeable_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order3d',
            name='junk_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
