# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_hash',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
