# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0003_order_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffcomment',
            name='public',
        ),
        migrations.AddField(
            model_name='comment',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
