# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0004_auto_20170822_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcustomer',
            name='order_token',
            field=models.CharField(default='2sdfsdfsd', max_length=30),
            preserve_default=False,
        ),
    ]
