# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0005_externalcustomer_order_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printing.Customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printing.Order')),
            ],
        ),
    ]
