# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0007_subscription_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='token',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
