# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0008_auto_20170828_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mail_address',
            field=models.EmailField(max_length=254),
        ),
    ]
