# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('printing', '0010_order_assignee'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistoryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistoryExternalEntry',
            fields=[
                ('orderhistoryentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='printing.OrderHistoryEntry')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printing.Customer')),
            ],
            bases=('printing.orderhistoryentry',),
        ),
        migrations.CreateModel(
            name='OrderHistoryStaffEntry',
            fields=[
                ('orderhistoryentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='printing.OrderHistoryEntry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('printing.orderhistoryentry',),
        ),
        migrations.AddField(
            model_name='orderhistoryentry',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printing.Order'),
        ),
    ]
