# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 18:37
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import printing.handlers


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0011_auto_20170829_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='/opt/pms/'), upload_to=printing.handlers.order_files_upload_handler),
        ),
        migrations.AddField(
            model_name='order',
            name='file_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
