# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 20:54
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import printing.handlers


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0012_auto_20170831_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file_thumbnail_path',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='/opt/pms/orders'), upload_to=printing.handlers.order_files_upload_handler),
        ),
    ]
