# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0013_auto_20170831_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Open'), (2, 'In Progress'), (3, 'Denied'), (4, 'Printing'), (5, 'Done')], default=0),
        ),
    ]
