# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('printing', '0016_customgroupfilters'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroupfilters',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
    ]
