# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0017_customgroupfilters_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroupfilters',
            name='key',
            field=models.CharField(max_length=40),
        ),
    ]
