# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 11:22
from __future__ import unicode_literals

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import printing.handlers


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0021_customgroupfilter_value_boolean'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterModelOptions(
            name='orderhistoryentry',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(default=None, null=True, storage=django.core.files.storage.FileSystemStorage(location='/opt/pms/orders'), upload_to=printing.handlers.order_files_upload_handler, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'stl'])]),
        ),
    ]
