# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0022_auto_20170902_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterModelOptions(
            name='orderhistoryentry',
            options={'ordering': ['create_date']},
        ),
    ]
