# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverSheetColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('color_code', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrder2d',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='printing.Order')),
                ('sided_printing', models.SmallIntegerField(choices=[(1, 'Simplex'), (2, 'Duplex')], default=1)),
                ('chromatic_printing', models.BooleanField(default=False)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printing.CostCenter')),
            ],
            bases=('printing.order',),
        ),
        migrations.CreateModel(
            name='Material2d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_weight', models.IntegerField()),
                ('paper_format', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PostProcessing2d',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='printing.Order')),
                ('cover_sheet_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printing_2d.CoverSheetColor')),
            ],
            bases=('printing.order',),
        ),
        migrations.AddField(
            model_name='customorder2d',
            name='post_processing',
            field=models.ManyToManyField(to='printing_2d.PostProcessing2d'),
        ),
    ]
