# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printing_2d', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customorder2d',
            options={'permissions': (('can_view', 'Can view'),)},
        ),
        migrations.AlterModelOptions(
            name='scriptorder',
            options={'permissions': (('can_view', 'Can view'),)},
        ),
    ]
