# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printing_2d', '0002_auto_20170902_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptorder',
            options={'permissions': (('can_view_scriptorder', 'Can view script order'),)},
        ),
    ]
