# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printing_2d', '0003_auto_20170902_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customorder2d',
            options={'permissions': (('view_customorder2d', 'Can view'),)},
        ),
        migrations.AlterModelOptions(
            name='scriptorder',
            options={'permissions': (('view_scriptorder', 'Can view script order'),)},
        ),
    ]
