# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing_2d', '0004_auto_20170902_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder2d',
            name='number_of_pages',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='scriptorder',
            name='number_of_pages',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
